/* ============================================================
 * Legacy Teradata DDL \u2014 customer dimension
 * Estate: ENTERPRISE_DW
 * Original author: legacy team, 2014
 * ============================================================ */

CREATE MULTISET TABLE ENTERPRISE_DW.CUSTOMER_DIM ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      CUSTOMER_ID         INTEGER NOT NULL,
      CUSTOMER_NAME       VARCHAR(120) CHARACTER SET LATIN NOT CASESPECIFIC,
      EMAIL               VARCHAR(200) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS,
      COUNTRY_CODE        CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('US','CA','MX','BR','AR','CO','PE','CL'),
      CUSTOMER_SEGMENT    VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('RETAIL','SMB','ENTERPRISE'),
      CREATED_TS          TIMESTAMP(0),
      UPDATED_TS          TIMESTAMP(0),
      ACTIVE_FLAG         BYTEINT COMPRESS 1
     )
PRIMARY INDEX ( CUSTOMER_ID )
INDEX ( EMAIL )
INDEX ( COUNTRY_CODE );

COLLECT STATISTICS COLUMN (CUSTOMER_ID) ON ENTERPRISE_DW.CUSTOMER_DIM;
COLLECT STATISTICS COLUMN (COUNTRY_CODE) ON ENTERPRISE_DW.CUSTOMER_DIM;
