/* ============================================================
 * Legacy Teradata DDL \u2014 sales fact (partitioned)
 * Estate: ENTERPRISE_DW
 * Volume: ~2.4 B rows / year
 * ============================================================ */

CREATE MULTISET TABLE ENTERPRISE_DW.SALES_FACT ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      SALE_ID            BIGINT NOT NULL,
      CUSTOMER_ID        INTEGER NOT NULL,
      PRODUCT_ID         INTEGER NOT NULL,
      STORE_ID           INTEGER COMPRESS,
      SALE_DATE          DATE FORMAT 'YYYY-MM-DD' NOT NULL,
      SALE_TS            TIMESTAMP(0),
      QUANTITY           DECIMAL(10,2),
      UNIT_PRICE         DECIMAL(12,4),
      DISCOUNT_PCT       DECIMAL(5,4) COMPRESS 0.0000,
      TAX_AMOUNT         DECIMAL(12,4),
      TOTAL_AMOUNT       DECIMAL(14,4),
      CURRENCY_CODE      CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('USD','EUR','MXN','BRL','ARS'),
      CHANNEL            VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC COMPRESS ('WEB','STORE','MOBILE','PARTNER'),
      LOAD_TS            TIMESTAMP(0)
     )
PRIMARY INDEX ( SALE_ID )
PARTITION BY RANGE_N(
     SALE_DATE BETWEEN DATE '2018-01-01' AND DATE '2030-12-31' EACH INTERVAL '1' MONTH,
     NO RANGE OR UNKNOWN
);

COLLECT STATISTICS COLUMN (SALE_DATE) ON ENTERPRISE_DW.SALES_FACT;
COLLECT STATISTICS COLUMN (CUSTOMER_ID) ON ENTERPRISE_DW.SALES_FACT;
COLLECT STATISTICS COLUMN (PRODUCT_ID) ON ENTERPRISE_DW.SALES_FACT;
