# Perfil de desarrollo — usa MongoDB embebido (Flapdoodle)
# No necesitas instalar MongoDB para ejecutar con este perfil.
spring.data.mongodb.database=products_dev_db

# Version de MongoDB embebido que descargará Flapdoodle
de.flapdoodle.mongodb.embedded.version=7.0.2

# Logging más detallado en dev
logging.level.com.example.springcrudms=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
